# Generated by Django 4.2.28 on 2026-02-08 15:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#95a5a6', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#3498db', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='core.department')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TicketEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('INT', 'Internal (Office)'), ('EXT', 'External (On-Site)'), ('REM', 'Remote Support'), ('ADM', 'Admin / Workshop')], default='INT', max_length=3)),
                ('status', models.CharField(choices=[('COMP', 'Completed'), ('BLOCK', 'Blocker'), ('PEND', 'Pending'), ('HOLD', 'On Hold'), ('CALL', 'Call Back'), ('WAIT_ST', 'Awaiting Staff'), ('WAIT_CL', 'Awaiting Client')], default='COMP', max_length=7)),
                ('work_location', models.CharField(choices=[('OFFICE', 'Office'), ('HOME', 'Work from Home'), ('HYBRID', 'Hybrid / Travel')], default='OFFICE', max_length=10)),
                ('requested_time', models.TimeField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('travel_start_time', models.TimeField(blank=True, null=True)),
                ('travel_end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('manager_ticket_notes', models.TextField(blank=True)),
                ('total_work_minutes', models.PositiveIntegerField(default=0)),
                ('travel_minutes', models.PositiveIntegerField(default=0)),
                ('response_minutes', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.client')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.dailyreport')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_entries', to='core.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_uploads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.ticketentry')),
            ],
        ),
        migrations.CreateModel(
            name='StaffWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('VERBAL', 'Verbal Warning'), ('WRITTEN', 'Written Warning'), ('FINAL', 'Final Warning'), ('PIP', 'Performance Improvement Plan')], max_length=10)),
                ('reason', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='hr_warnings/')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='core.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ratingcriteria')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.dailyreport')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='core.staffprofile')),
            ],
            options={
                'ordering': ['staff', 'criteria'],
                'unique_together': {('report', 'staff', 'criteria')},
            },
        ),
    ]
