# Generated by Django 4.2.28 on 2026-02-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_checkformfolder_scheduleslot_schedulechangelog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkformtemplate",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AlterField(
            model_name="scheduleslot",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PENDING_DELETE", "Pending Deletion"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
