# Generated by Django 4.2.28 on 2026-02-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_scheduleslot_status'),
        ('core', '0003_checkformtemplate_company_logo_and_more'),
    ]

    operations = [
    ]
